version: '3'

networks:
  my-network:
    name: backend
    driver: bridge

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    ports:
     - "8080:8080"
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=password
     - KC_HOSTNAME=host.docker.internal
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway" #FOR UNIX

  eureka-microservice:
    image: eureka-microservice:1.0.0.
    ports:
      - "8761:8761"
    depends_on:
      - keycloak
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway" #FOR UNIX

  gateway-microservice:
    image: gateway-microservice:1.0.0.
    ports:
     - "8760:8760"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-microservice:8761/eureka
    depends_on:
      - keycloak
      - eureka-microservice
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway" #FOR UNIX

  date-microservice:
    image: date-microservice:1.0.0.
    ports:
     - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-microservice:8761/eureka
      - AUTH_URLS=http://host.docker.internal:8080/realms/microservices
    depends_on:
      - keycloak
      - eureka-microservice
      - gateway-microservice
    extra_hosts:
      - "host.docker.internal:host-gateway" #FOR UNIX
    networks:
      - my-network

  time-microservice:
    image: time-microservice:1.0.0.
    ports:
     - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-microservice:8761/eureka
      - AUTH_URLS=http://host.docker.internal:8080/realms/microservices
    depends_on:
      - keycloak
      - eureka-microservice
      - gateway-microservice
      - date-microservice
    extra_hosts:
      - "host.docker.internal:host-gateway" #FOR UNIX
    networks:
      - my-network

  angular-app:
    build:
      context: ./skeleton_frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
