version: '1'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    ports:
     - "8080:8080"
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=password
     - KC_HOSTNAME=keycloak
    networks:
      - backend

  eureka-microservice:
    image: eureka-microservice:1.0.0.
    ports:
      - "8761:8761"
    depends_on:
      - keycloak
    networks:
      - backend

  gateway-microservice:
    image: gateway-microservice:1.0.0.
    ports:
     - "8760:8760"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-microservice:8761/eureka
    depends_on:
      - keycloak
      - eureka-microservice
    networks:
      - backend

  date-microservice:
    image: date-microservice:1.0.0.
    ports:
     - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-microservice:8761/eureka
      - AUTH_URLS=http://keycloak:8080/realms/microservices
    depends_on:
      - keycloak
      - eureka-microservice
      - gateway-microservice
    networks:
      - backend

  time-microservice:
    image: time-microservice:1.0.0.
    ports:
     - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-microservice:8761/eureka
      - AUTH_URLS=http://keycloak:8080/realms/microservices
    depends_on:
      - keycloak
      - eureka-microservice
      - gateway-microservice
      - date-microservice
    networks:
      - backend

networks:
  backend:
    driver: bridge
